FROM node:22.11-alpine as node

WORKDIR /app

COPY . .

RUN npm install -y

RUN npm run build

FROM nginx:1.27-alpine

COPY --from=node  /app/dist/* /usr/share/nginx/html

COPY nginx /etc/nginx

COPY entrypoint.sh /docker-entrypoint.d/entrypoint.sh
RUN chmod +x /docker-entrypoint.d/entrypoint.sh

